# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

# Header
language: r: 3.4.2
r: 
  - devel
warnings_are_errors: false
sudo: false
cache: packages

r_build_args: "--no-build-vignettes --no-manual --no-resave-data"
r_check_args: "--no-build-vignettes --no-manual"



